import os

AWS_REGION = os.environ.get("AWS_REGION", "us-east-1")

DYNAMODB_TABLE_DELIVERY_ASSIGNMENTS = os.environ.get("DYNAMODB_TABLE_DELIVERY_ASSIGNMENTS", "delivery_assignments")
DYNAMODB_TABLE_COURIER_STATES = os.environ.get("DYNAMODB_TABLE_COURIER_STATES", "courier_states")
DYNAMODB_TABLE_ORDER_EVENTS = os.environ.get("DYNAMODB_TABLE_ORDER_EVENTS", "order_events")

SNS_TOPIC_ARN_ORDER_EVENTS = os.environ.get("SNS_TOPIC_ARN_ORDER_EVENTS", "")
SQS_QUEUE_URL_DELIVERY_EVENTS = os.environ.get("SQS_QUEUE_URL_DELIVERY_EVENTS", "")

SUPABASE_URL = os.environ.get("SUPABASE_URL", "")
SUPABASE_SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")

ORDER_SERVICE_URL = os.environ.get("ORDER_SERVICE_URL", "")
WAZE_API_KEY = os.environ.get("WAZE_API_KEY", "")

MAX_COURIER_DISTANCE_MINUTES = int(os.environ.get("MAX_COURIER_DISTANCE_MINUTES", "15"))
GPS_SYNC_INTERVAL_SECONDS = int(os.environ.get("GPS_SYNC_INTERVAL_SECONDS", "600"))
SQS_POLL_INTERVAL_SECONDS = int(os.environ.get("SQS_POLL_INTERVAL_SECONDS", "5"))

LOG_LEVEL = os.environ.get("LOG_LEVEL", "INFO")
ENVIRONMENT = os.environ.get("ENVIRONMENT", "dev")
